{% set name = "mkapi" %}
{% set version = "3.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkapi-{{ version }}.tar.gz
  sha256: aec8a244e3c74c6bf5d93bb91b7bb25d8ac3e3960b85d21265f55346fc809958

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.10
    - hatchling
  run:
    - jinja2
    - python >=3.10
    - halo
    - tqdm
    - mkdocs-material

test:
  imports:
    - mkapi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://daizutabi.github.io/mkapi/
  summary: An Auto API Documentation tool.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - hadim
