{% set name = "mkapi" %}
{% set version = "2.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkapi-{{ version }}.tar.gz
  sha256: d86c3244b518dc89094520c4b4f67beaf831b866754bfebf99cd8a426951a152

build:
  number: 0
  noarch: python
  entry_points:
    - mkapi = mkapi.main:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - jinja2
    - markdown
    - python >=3.7

test:
  imports:
    - mkapi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://mkapi.daizutabi.net
  summary: An Auto API Documentation tool.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
