{% set name = "mkapi" %}
{% set version = "2.0.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkapi-{{ version }}.tar.gz
  sha256: e633e7da4182376fc8b85d40f02f9d899e3a494a550193764f2431eea8353609

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.10
    - hatchling
  run:
    - jinja2
    - python >=3.10
    - halo
    - tqdm
    - mkdocs-material

test:
  imports:
    - mkapi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://daizutabi.github.io/mkapi/
  summary: An Auto API Documentation tool.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - hadim
