{% set name = "mkapi" %}
{% set version = "2.0.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkapi-{{ version }}.tar.gz
  sha256: 59bc205b16ad7fb6e17990c5b8f6de212f2d7f0f66e7a1d7bb4982d36c2e683b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.10
    - hatchling
  run:
    - jinja2
    - python >=3.10
    - halo
    - tqdm
    - mkdocs-material

test:
  imports:
    - mkapi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://daizutabi.github.io/mkapi/
  summary: An Auto API Documentation tool.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - hadim
