{% set name = "mkapi" %}
{% set version = "2.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkapi-{{ version }}.tar.gz
  sha256: a3f90b2fbac81c28cb3291c3183cb52727522641c9da591025600e3367028bde

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.10
    - hatchling
  run:
    - jinja2
    - python >=3.10
    - halo
    - tqdm
    - mkdocs-material

test:
  imports:
    - mkapi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://daizutabi.github.io/mkapi/
  summary: An Auto API Documentation tool.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - hadim
